//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtoCommerce.CustomerModule.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MemberResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MemberResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtoCommerce.CustomerModule.Data.Resources.MemberResources", typeof(MemberResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address &apos;{0}&apos; added.
        /// </summary>
        public static string AddressAdded {
            get {
                return ResourceManager.GetString("AddressAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address &apos;{0}&apos; deleted.
        /// </summary>
        public static string AddressDeleted {
            get {
                return ResourceManager.GetString("AddressDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address  &apos;{0}&apos; changed to &apos;{1}&apos;.
        /// </summary>
        public static string AddressModified {
            get {
                return ResourceManager.GetString("AddressModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email &apos;{0}&apos; added.
        /// </summary>
        public static string EmailAdded {
            get {
                return ResourceManager.GetString("EmailAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email &apos;{0}&apos; deleted.
        /// </summary>
        public static string EmailDeleted {
            get {
                return ResourceManager.GetString("EmailDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; changed from &apos;{1}&apos; to &apos;{2}&apos;.
        /// </summary>
        public static string MemberPropertyChanged {
            get {
                return ResourceManager.GetString("MemberPropertyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone &apos;{0}&apos; added.
        /// </summary>
        public static string PhoneAdded {
            get {
                return ResourceManager.GetString("PhoneAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone &apos;{0}&apos; deleted.
        /// </summary>
        public static string PhoneDeleted {
            get {
                return ResourceManager.GetString("PhoneDeleted", resourceCulture);
            }
        }
    }
}
