//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtoCommerce.CustomerModule.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MemberResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MemberResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtoCommerce.CustomerModule.Data.Resources.MemberResources", typeof(MemberResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address &apos;{2}&apos; for {0} {1} added.
        /// </summary>
        public static string AddressAdded {
            get {
                return ResourceManager.GetString("AddressAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address &apos;{2}&apos; for {0} {1} deleted.
        /// </summary>
        public static string AddressRemoved {
            get {
                return ResourceManager.GetString("AddressRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email &apos;{2}&apos; for {0} {1} added.
        /// </summary>
        public static string EmailAdded {
            get {
                return ResourceManager.GetString("EmailAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email &apos;{2}&apos; for {0} {1} deleted.
        /// </summary>
        public static string EmailRemoved {
            get {
                return ResourceManager.GetString("EmailRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new {0} {1} added.
        /// </summary>
        public static string MemberAdded {
            get {
                return ResourceManager.GetString("MemberAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} {1} deleted.
        /// </summary>
        public static string MemberDeleted {
            get {
                return ResourceManager.GetString("MemberDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} {1} property &apos;{2}&apos; changed from &apos;{3}&apos; to  &apos;{4}&apos;.
        /// </summary>
        public static string MemberPropertyChanged {
            get {
                return ResourceManager.GetString("MemberPropertyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone &apos;{2}&apos; for {0} {1} added.
        /// </summary>
        public static string PhoneAdded {
            get {
                return ResourceManager.GetString("PhoneAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone &apos;{2}&apos; for {0} {1} deleted.
        /// </summary>
        public static string PhoneRemoved {
            get {
                return ResourceManager.GetString("PhoneRemoved", resourceCulture);
            }
        }
    }
}
