// <auto-generated />
namespace VirtoCommerce.CustomerModule.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class MemberGroups : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MemberGroups));
        
        string IMigrationMetadata.Id
        {
            get { return "201611171903485_MemberGroups"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
